
# Usando a imagem oficial do PHP com Apache
FROM php:8.1-apache

# Instalar as extensões necessárias para PostgreSQL
RUN docker-php-ext-install pdo pdo_pgsql

# Copiar os arquivos do projeto para o contêiner
COPY . /var/www/html/

# Definir diretório de trabalho
WORKDIR /var/www/html/

# Expor a porta 80 para acessar o Apache
EXPOSE 80
