version: '3.8'

services:
  # Serviço para o PostgreSQL
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_senha
      POSTGRES_DB: usuarios
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Serviço para o Apache/PHP
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_php_app
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
